name: Docker CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t mownika06/docker-workshop .

      - name: List Docker Images
        run: docker images

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push mownika06/docker-workshop