name: Build Docker image
on: [push]
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run Docker Build
              run: docker build -t pythonimage .
               
              
              